services:
  netty-socks-server:
    image: "acr.kubectl.net/svcops/netty-socks-server"
    ports:
      - "1080:1080"
    volumes:
      - ./logs:/opt/app/logs
    environment:
      - TZ=Asia/Shanghai
      - JAVA_OPTS=-Xmx128m -Xms128m
      - SERVER_PORT=1080
      # - SOCKS5_USERNAME=admin # optional
      # - SOCKS5_PASSWORD=admin # optional
