services:
  netty-server-tcp-test:
    image: "svcops/netty-server-tcp-test"
    ports:
      - "8080:8080"
    environment:
      - TZ=Asia/Shanghai
      - SERVER_PORT=8080
      - TEST_TYPE=log
      - JAVA_OPTS=-Xmx128m -Xms128m