[versions]
java = "21"
kotlin = "2.3.0"

spring-boot = "3.4.12"

# protobuf = "3.24.3"
protobuf = "4.33.2"
grpc = "1.77.0"
spring-boot-starter-grpc = "3.1.0.RELEASE"

jackson = "3.0.1"
commons-lang3 = "3.20.0"
netty-all = "4.2.9.Final"
logback = "1.5.27"
slf4j = "2.0.17"
junit-jupiter = "6.0.2"
fastjson2 = "2.0.60"
commons-io = "2.21.0"

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-spring = { id = "org.jetbrains.kotlin.plugin.spring", version.ref = "kotlin" }

spring-boot = { id = "org.springframework.boot", version.ref = "spring-boot" }
spring-dependency-management = { id = "io.spring.dependency-management", version = "1.1.6" }

[libraries]
commons-lang3 = { module = "org.apache.commons:commons-lang3", version.ref = "commons-lang3" }
netty-all = { module = "io.netty:netty-all", version.ref = "netty-all" }
logback-classic = { module = "ch.qos.logback:logback-classic", version.ref = "logback" }
logback-core = { module = "ch.qos.logback:logback-core", version.ref = "logback" }
slf4j-api = { module = "org.slf4j:slf4j-api", version.ref = "slf4j" }

fastjson2 = { module = "com.alibaba.fastjson2:fastjson2", version.ref = "fastjson2" }
kotlin-reflect = { module = "org.jetbrains.kotlin:kotlin-reflect", version.ref = "kotlin" }

commons-io = { module = "commons-io:commons-io", version.ref = "commons-io" }

junit-jupiter-api = { module = "org.junit.jupiter:junit-jupiter-api", version.ref = "junit-jupiter" }
junit-jupiter-engine = { module = "org.junit.jupiter:junit-jupiter-engine", version.ref = "junit-jupiter" }
junit-platform-launcher = { module = "org.junit.platform:junit-platform-launcher", version.ref = "junit-jupiter" }

jackson-core = { module = "tools.jackson.core:jackson-core", version.ref = "jackson" }
jackson-databind = { module = "tools.jackson.core:jackson-databind", version.ref = "jackson" }
jackson-annotations = { module = "com.fasterxml.jackson.core:jackson-annotations", version = "2.20" }
jackson-module-kotlin = { module = "tools.jackson.module:jackson-module-kotlin", version.ref = "jackson" }
