[versions]
freefair-lombok = "8.13.1"
java = "21"
kotlin = "2.2.21"

spring-boot = "3.2.10"
protoc = "3.24.3"
grpc = "1.76.0"
grp-spring-boot-starter = "3.1.0.RELEASE"
jackson = "3.0.1"
commons-lang3 = "3.20.0"
netty-all = "4.1.115.Final"
logback = "1.5.21"
slf4j = "2.0.12"
junit-jupiter = "6.0.1"
fastjson2 = "2.0.60"
commons-io = "2.21.0"

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-spring = { id = "org.jetbrains.kotlin.plugin.spring", version.ref = "kotlin" }

google-protobuf = { id = "com.google.protobuf", version = "0.9.5" }
spring-boot = { id = "org.springframework.boot", version.ref = "spring-boot" }
spring-dependency-management = { id = "io.spring.dependency-management", version = "1.1.6" }

[libraries]
commons-lang3 = { module = "org.apache.commons:commons-lang3", version.ref = "commons-lang3" }
netty-all = { module = "io.netty:netty-all", version.ref = "netty-all" }
logback-classic = { module = "ch.qos.logback:logback-classic", version.ref = "logback" }
logback-core = { module = "ch.qos.logback:logback-core", version.ref = "logback" }
slf4j-api = { module = "org.slf4j:slf4j-api", version.ref = "slf4j" }

fastjson2 = { module = "com.alibaba.fastjson2:fastjson2", version.ref = "fastjson2" }
kotlin-reflect = { module = "org.jetbrains.kotlin:kotlin-reflect", version.ref = "kotlin" }

commons-io = { module = "commons-io:commons-io", version.ref = "commons-io" }

junit-jupiter-api = { module = "org.junit.jupiter:junit-jupiter-api", version.ref = "junit-jupiter" }
junit-jupiter-engine = { module = "org.junit.jupiter:junit-jupiter-engine", version.ref = "junit-jupiter" }
junit-platform-launcher = { module = "org.junit.platform:junit-platform-launcher", version.ref = "junit-jupiter" }


grpc-protobuf = { module = "io.grpc:grpc-protobuf", version = "1.76.0" }
grpc-services = { module = "io.grpc:grpc-services", version = "1.76.0" }
grpc-stub = { module = "io.grpc:grpc-stub", version = "1.76.0" }
grpc-netty-shaded = { module = "io.grpc:grpc-netty-shaded", version = "1.76.0" }
grpc-spring-boot-starter = { module = "net.devh:grpc-spring-boot-starter", version.ref = "grp-spring-boot-starter" }
grpc-client-spring-boot-starter = { module = "net.devh:grpc-client-spring-boot-starter", version.ref = "grp-spring-boot-starter" }
grpc-server-spring-boot-starter = { module = "net.devh:grpc-server-spring-boot-starter", version.ref = "grp-spring-boot-starter" }

jackson-core = { module = "tools.jackson.core:jackson-core", version.ref = "jackson" }
jackson-databind = { module = "tools.jackson.core:jackson-databind", version.ref = "jackson" }
jackson-annotations = { module = "com.fasterxml.jackson.core:jackson-annotations", version = "2.20" }
jackson-module-kotlin = { module = "tools.jackson.module:jackson-module-kotlin", version.ref = "jackson" }

spring-boot = { module = "org.springframework.boot:spring-boot", version.ref = "spring-boot" }
spring-boot-starter-logging = { module = "org.springframework.boot:spring-boot-starter-logging", version.ref = "spring-boot" }
