services:
  netty-server-tcp-test:
    image: "svcops/netty-tcp-server-test"
    ports:
      - "8080:8080"
    volumes:
      - ./logs:/opt/app/logs
    environment:
      - TZ=Asia/Shanghai
      - SERVER_PORT=8080
      - TEST_TYPE=log
      - JAVA_OPTS=-Xmx128m -Xms128m
