name: Build and Push svcops/netty-server-tcp-test image

on:
  push:
    branches: [ main ]
  workflow_dispatch:

concurrency:
  group: netty-server-tcp-test-${{ github.ref }}    # 按分支分组
  # 有新触发时取消同组在途运行
  cancel-in-progress: ${{ github.event_name == 'workflow_dispatch' || contains(github.event.head_commit.message, 'build_tcp_test') }}

jobs:
  build-netty-server-tcp-test:
    name: Build and Push svcops/netty-server-tcp-test image
    runs-on: ubuntu-latest
    # 支持手动构建和提交信息中存在关键字 build_ubuntu-ext
    if: >-
      github.event_name == 'workflow_dispatch' || 
      contains(github.event.head_commit.message, 'build_tcp_test')

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Registries
        uses: .github/actions/docker-login
        with:
          dockerhub-username: ${{ secrets.DOCKERHUB_USERNAME }}
          dockerhub-password: ${{ secrets.DOCKERHUB_PASSWORD }}
          aliyun-registry: ${{ secrets.ALIYUN_REGISTRY }}
          aliyun-username: ${{ secrets.ALIYUN_USERNAME }}
          aliyun-password: ${{ secrets.ALIYUN_PASSWORD }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and Push svcops/netty-server-tcp-test image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile
          push: true
          tags: |
            svcops/netty-server-tcp-test:latest
            ${{ secrets.ALIYUN_REGISTRY }}/svcops/netty-server-tcp-test:latest
          build-args: |
            SUB_MODULE=netty-server-tcp-test
            JAR_NAME=netty-server-tcp-test-1.0-all.jar
