name: Build and Push svcops/netty-server-tcp-proxy image

on:
  push:
    branches: [ main ]
  workflow_dispatch:

concurrency:
  group: netty-server-tcp-proxy-${{ github.ref }}    # 按分支分组
  # 有新触发时取消同组在途运行
  cancel-in-progress: ${{ github.event_name == 'workflow_dispatch' || contains(github.event.head_commit.message, 'build_tcp_proxy') }}

jobs:
  build-netty-server-tcp-proxy:
    name: Build and Push svcops/netty-server-tcp-proxy image
    runs-on: ubuntu-latest
    # 支持手动构建和提交信息中存在关键字 build_ubuntu-ext
    if: >-
      github.event_name == 'workflow_dispatch' || 
      contains(github.event.head_commit.message, 'build_tcp_proxy')

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Docker Login (DockerHub,ACR)
        uses: ./.github/actions/docker-login
        with:
          dockerhub_username: ${{ secrets.DOCKERHUB_USERNAME }}
          dockerhub_password: ${{ secrets.DOCKERHUB_PASSWORD }}
          aliyun_registry: ${{ secrets.ALIYUN_REGISTRY }}
          aliyun_username: ${{ secrets.ALIYUN_USERNAME }}
          aliyun_password: ${{ secrets.ALIYUN_PASSWORD }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and Push svcops/netty-server-tcp-proxy image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile
          push: true
          tags: |
            svcops/netty-server-tcp-proxy:latest
            ${{ secrets.ALIYUN_REGISTRY }}/svcops/netty-server-tcp-proxy:latest
          build-args: |
            SUB_MODULE=netty-server-tcp-proxy
            JAR_NAME=netty-server-tcp-proxy-1.0-all.jar
